#!/usr/bin/env sh
#
# Gradle startup script for POSIX
# Generated by backup bootstrap.
# Optimized for BioAcupunt Supremo CI path.

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_NAME="Gradle"
GRADLE_VERSION="8.11"

# Resolve the location of this script.
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done
PRGDIR=`dirname "$PRG"`

# Set up environment
GRADLE_HOME="$PRGDIR/gradle/wrapper/dists/gradle-$GRADLE_VERSION-bin"

# try wrapper JAR first, fallback to bin if dist exists
if [ -f "$PRGDIR/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec java $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
        -Dorg.gradle.appname="$APP_NAME" \
        -classpath "$PRGDIR/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain "$@"
else
    exec "$PRGDIR/gradle/bin/gradle" "$@"
fi
